# Generated by Django 2.2.2 on 2020-02-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_tempaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempaccount',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
