# Generated by Django 2.2.2 on 2020-02-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_tempaccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempaccount',
            name='expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
