# Generated by Django 2.2.2 on 2020-03-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_tempaccount_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='shop',
        ),
    ]
