# Generated by Django 2.2.2 on 2020-03-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
