# Generated by Django 2.2.2 on 2020-03-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_complaint_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='replied',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
